name: Deploy Express.js Backend to Azure App Service

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry (ACR)
        run: |
          az acr login --name myacr.azurecr.io

      - name: Build Docker image
        run: |
          docker build -t myacr.azurecr.io/my-backend:v1 ./backend
          docker push myacr.azurecr.io/my-backend:v1

      - name: Deploy to Azure App Service
        run: |
          az webapp config container set \
            --resource-group my-resource-group \
            --name my-backend \
            --docker-custom-image-name myacr.azurecr.io/my-backend:v1

      - name: Restart the backend app
        run: |
          az webapp restart --name my-backend --resource-group my-resource-group
