/* Replace with your SQL commands */
-- Drop the tables in reverse order of creation to avoid foreign key constraint issues
DROP TABLE IF EXISTS USERS_CONFERENCE CASCADE;

DROP TABLE IF EXISTS BOOKMARKS CASCADE;

DROP TABLE IF EXISTS EVENTS CASCADE;

DROP TABLE IF EXISTS CONFERENCE CASCADE;

DROP TABLE IF EXISTS USERS CASCADE;

DROP TABLE IF EXISTS USERS_ROLES CASCADE;
